### ISSUE TITLE
Data table related shiny examples are not working in RCloud

### ISSUE THREAD

**Issue by prateek032** [att/rcloud.shiny#10]
When we open the notebook in shiny, the UI appears but it fails to generate the data table. 

![image](https://cloud.githubusercontent.com/assets/10941328/19995212/33437f90-a27b-11e6-94e8-4d8ee51373ac.png)

**Comment by gordonwoodhull** [comment]
As I mentioned on the call, we still are not compatible with "unproxified" RCloud servers, so I don't expect this to work on your local test server. 

Please test Shiny features on rcloud-5 for now. When I imported your notebook there, it seems to work, which is great!

**Comment by prateek032** [comment]
Confirmed. On RCloud-5 instance its working as expected.
