### ISSUE TITLE
Issue with rJava module loading in the platform

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud.shiny#15]
One of our users was utilizing our hit tracking solution on KM.  The url is https://rcloud.web.att.com/shiny.html?notebook=5628a8ac9c9ccf42480bcd60d8e0cef9&redirectToNotebook=e168bcbe5ee1fee910b4f2b5255b694b

The platform is throwing a library import error for rJava for anonymous users.  The console trace of the error is below:

session log;  2017-02-20 14:29:16 INFO::Decoding the session cookie

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.out']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=out, old.ctx=undefined
/js/rcloud_bundle.js:11668 session log;  2017-02-20 14:29:16 INFO::Decoding the session cookie

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.err']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=err, old.ctx=undefined
/js/rcloud_bundle.js:11668 session log;  Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/opt/app/R/lib64/R/library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.err']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=err, old.ctx=undefined
/js/rcloud_bundle.js:11668 session log;  In addition: Warning message:

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.err']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=err, old.ctx=undefined
/js/rcloud_bundle.js:11668 session log;  no DISPLAY variable so Tk is not available 

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.err']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=err, old.ctx=undefined
/js/rcloud_bundle.js:11668 session log;  Warning: Error in : package ‘rJava’ could not be loaded

/js/rcloud_bundle.js:4701 OOB send arrived: ['console.err']
/js/rcloud_bundle.js:4608 forward_to_context, ctx=OCAP-call, type=err, old.ctx=undefined

Please advise.

Best Regards,
Lance Jensen

**Comment by gordonwoodhull** [comment]
I get the same error if I'm logged in or logged out, so I don't think it has to do with anonymous users.

I guess it is probably a configuration problem on the server. 

Could you please file a ticket, or email me and I will forward to the appropriate people? It's clearly not an error in rcloud.shiny itself (as rcloud.shiny doesn't use rJava).

**Comment by LanceJensen-General** [comment]
Ok I will file the ticket. I do not use rJava in any of my dependencies but I assumed it was part of the platform when I saw the source errors.  I will forward you the ticket after I place it.

Thanks.

**Comment by s-u** [comment]
My guess - someone upgraded Java an didn't run `sudo R CMD javareconf`

**Comment by gordonwoodhull** [comment]
Thanks @s-u. 

@LanceJensen-General, it's probably the gateKeeper package that triggered this.

**Comment by LanceJensen-General** [comment]
Ok.  I will go and add that feedback to the ticket.
