### ISSUE TITLE
Shiny - renderDataTable not working

### ISSUE THREAD

**Issue by Chuck-Field** [att/rcloud.shiny#5]
I'm trying to create a table in shiny, using the function "renderDataTable" but I keep getting a json error. I have no problem using the renderTable function, but I can't format the table the way I want to see it. with "renderTable" and would prefer using "renderDataTable". 
I've read -
    rendertable uses xtable to create the html table
    renderDataTable uses external javascript library

Does RCloud have some kind of limitation with an external javascript library that is keeping me from making this "renderDataTable" function from working? 

Thanks for looking into this.

**Comment by gordonwoodhull** [comment]
Yes, rcloud.shiny does not offer complete Shiny support yet. This is one of the features known not to work yet.

We have added a couple of features into core RCloud that we think provide the basis to improve our compatibility, and we are hoping to release an improved rcloud.shiny in the next release, due this summer. I'll comment here when there's something to test on the develop branch of RCloud.

The features that **do currently work** can be found in the notebook folder 

RCloud Sample Notebooks/Dashboarding/RCloud shiny.html

on http://rcloud.social

**Comment by gordonwoodhull** [comment]
Thanks for reporting this, @Chuck-Field! The exact limitations are not currently documented, but you can extrapolate from what's in the Shiny gallery but not in the above folder.

**Comment by gordonwoodhull** [comment]
Fixed in rcloud.shiny 0.4 (RCloud 1.7)
