### ISSUE TITLE
Stick Shiny in an iframe?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.shiny#6]
We need some kind of two-stage loading for rcloud.shiny, because we first need to establish the RCloud session and then get Shiny to use it. 

Currently we start a variant of mini.html, create a hook so that Shiny will use ocaps instead of opening a new websocket, and then inject the Shiny-generated html into that page. It works but 
1. The page needs to make other http requests back to the Shiny server. Thus we now have [proxy.R](https://github.com/att/rcloud/blob/develop/htdocs/proxy.R)
2. Apparently the order of loading of javascript script tags by jQuery is not reliable unless you force it to load javascript synchronously, which causes browser responsiveness drag at best, and apparently also leads to deadlock if we poll from the client side as we [currently do](https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/R/rcloud.shiny.R#L85) in an [experimental branch](https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/inst/javascript/rcloud.shiny.js#L39-41) of shiny.rcloud 

All of this is just background for a simple question I'm getting to.

Using a full window iframe to give Shiny its own context was first suggested by @s-u as a throwaway idea. Last week @gaborcsardi suggested this more seriously.

So now I'm calling on everyone I know who's had more experience with iframes than I have (ping @shaneporter @salivian) to tell me what's wrong with 
- spawning the RCloud session in the main document 
- modifying the Shiny-generated index.html to first install [our hook](https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/inst/javascript/rcloud.shiny.js#L30-34), breaking rcloud.shiny.js into two stages 
- starting the Shiny server and polling it [as shown](https://github.com/att/rcloud.shiny/blob/feature/call-serviceApp/inst/javascript/rcloud.shiny.js#L39-41) 
- creating a full window iframe and launching index.html from the Shiny server via proxy.R 

?

**Comment by gordonwoodhull** [comment]
In particular, iframes are known to be brittle and annoying both to developers and to users. What are the potential problems I should look for if I implement this next week?

**Comment by gordonwoodhull** [comment]
Currently I am aware of these potential problems:
- URL of the page content will not match the URL of the window, and won't work on its own
- child frame will have its own browser history 

But I'm optimistic: since most of the annoyances are caused by a lack of cooperation between child and parent UI, these might be acceptable problems. (And can possibly be mitigated, since we can manipulate the child HTML.)

**Comment by gordonwoodhull** [comment]
Here's a comprehensive SO answer, in general terms: http://stackoverflow.com/a/23178537/676195

Of these, I think **difficulty to debug** and **plain difficult to keep stable** are concerns for us. To be glib, these are already major RCloud problems so perhaps no one will notice. To be serious, the problems will probably multiply each other, causing debugging RCloud to square in complexity.

**Comment by gordonwoodhull** [comment]
> A web worker or a cross-origin iframe has its own stack, heap, and message queue.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

Implying that a same-origin iframe, [which I think we need here to share the session and connection](http://stackoverflow.com/a/7647123/676195), is same-thread. But if we still run into deadlock, we could consider putting the Shiny poller into a web worker.

**Comment by gaborcsardi** [comment]
You can stick the iframe source in the page with the `srcdoc` attribute. That's what I am doing with htmlwidgets.

**Comment by gordonwoodhull** [comment]
Thanks @gaborcsardi, my reasoning for serving index.html (actually `/`) from Shiny itself is that anything in that ecosystem that uses a relative URL should be okay... even with our very strange proxy.R URLs, which contain the :port embedded in the path. 

Shiny does load js and css assets relatively afair; I'm just hoping that any Ajax calls also use the URL intact.

Of course there is no way of knowing all the assumptions built into that ecosystem, with all the third party Shiny plugins and htmlwidgets. Any client-server model where there is only one implementation of the server is likely to be messy.

**Comment by gordonwoodhull** [comment]
BTW, htmltools does have a facility for rewriting URLs and we are using it in the experiment linked above (which contains a small but temporary GPL violation). But I'm pessimistically assuming that not all URLs will be passed through htmltools, or will be constructed after the initial load.

**Comment by gordonwoodhull** [comment]
@gaborcsardi, hopefully there is enough information here to try this idea out. As linked in the first comment, most of the techniques are implemented in the `feature/call-serviceApp` branch, but this still uses the injection-into-mini.html approach, which is costly and can load javascript in the wrong order.

I'll assign you this issue once you accept your invitation to collaborate on the project.

**Comment by gordonwoodhull** [comment]
This is the heart of rcloud.shiny 0.4
