### ISSUE TITLE
move shiny.html and script from RCloud

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.shiny#7]
We can serve shiny.html and require-shiny.js from the www/ directory using RCloud's shared.R, making rcloud.shiny self-contained. This will help as we evolve the implementation separately from RCloud's release schedule.

**Comment by useless5771** [comment]
Pull requests:
* https://github.com/att/rcloud.shiny/pull/19
* https://github.com/att/rcloud/pull/2435
